Feat/342 adgk china
AdguardTeam/FiltersRegistry pull request #343
Opened 2020-05-25 17:01 UTC by Alex-302

Replaced obsolete Prebake filter.
Not sure about trustLevel.

2020-05-29 12:03 UTC, krystian3w commented
Maybe need _high_  to work `mp4`/`empty` moddifier.

```
.atm.cp31.ott.cibntv.net$media,MP4
||valipl.cp31.ott.cibntv.net^$domain=v.youku.com,mp4,media
||cdn-adn.rayjump.com/cdn-adn/*.mp4$app=com.naga.kun,mp4
||vali.cp31.ott.cibntv.net/youku/*/*.mp4*$app=com.huawei.hwvplayer.youku,mp4
||*/youku/*/*.mp4*vali.cp31.ott.cibntv.net*$app=com.huawei.hwvplayer.youku,mp4
||vali.cp31.ott.cibntv.net/youku^$domain=v.youku.com,mp4
```
```
||cpoml.iask.sina.com.cn^$empty
||sl.sogoucdn.com/semob$empty,popup
/?encrypt=$empty,app=com.tencent.mtt.intl
```

2020-06-22 09:52 UTC, slavaleleka commented
@krystian3w 
modifiers `mp4` and `empty` are not related to trust levels

2020-06-22 09:58 UTC, krystian3w commented
So can work on `low` - no use `+js()` or `redirect=` or  `{ style: css }`.

2020-06-22 10:02 UTC, krystian3w commented
I found invalid CSS (`##` instead of `#$#`) - if this no problem for `filterCompler` so need for 1 filter `high` instead of `low`.

`chinanews.com##.enter_top {    width: 100%;    height: 154px;    background: #fff;}`

---

this is strange:

```
(function() {
var hm = document.createElement("script");
var s = document.getElementsByTagName("script")[0];
s.parentNode.insertBefore(hm, s);
})();
```

little JS almost in the middle of the file.

2020-06-22 18:54 UTC, ameshkov commented
> little JS almost in the middle of the file.

Yeah, this is quite weird indeed

2020-06-22 18:58 UTC, Alex-302 commented
Maybe wrong copy-pasta. Looks like a part of Baidu tracker.

2020-07-21 07:11 UTC, banbendalao commented
The warehouse has been urgently migrated https://github.com/banbendalao/ADgk

2020-07-23 11:36 UTC, Alex-302 commented
@banbendalao please take a look https://github.com/banbendalao/ADgk/issues/1

2021-07-13 16:56 UTC, zloyden requested changes

2021-07-13 16:56 UTC, zloyden commented on filters/ThirdParty/filter_209_ADgkMobileChina/metadata.json
> +  "homepage": "http://adgk.net/",
Now the home page `https://github.com/banbendalao/ADgk`.

2021-07-13 16:59 UTC, zloyden commented
@Alex-302 please resolve conflicts and review it again. @banbendalao removed problematic rules.

2022-07-21 07:22 UTC, closed without merging