Updated hufilter metadata
AdguardTeam/FiltersRegistry pull request #375
Opened 2020-08-19 17:16 UTC by Alex-302

2020-08-19 18:55 UTC, slavaleleka approved these changes

2020-08-20 07:28 UTC, ameshkov requested changes

2020-08-20 07:28 UTC, ameshkov commented on filters/ThirdParty/filter_203_hufilter/metadata.json
> +  "name": "Magyar szűrő",
Let's keep English name and description here. We'd better localize it later.

2020-08-20 07:28 UTC, ameshkov commented on filters/ThirdParty/filter_203_hufilter/metadata.json
> +  "subscriptionUrl": "https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-adguard.txt",
Don't forget to change the filter template

2020-08-20 09:27 UTC, ameshkov approved these changes

2020-08-20 09:28 UTC, merged