Third-party filter lists metadata for Crowdin
AdguardTeam/FiltersRegistry pull request #391
Opened 2020-11-02 15:12 UTC by slavaleleka

https://github.com/AdguardTeam/FiltersRegistry/issues/390

2020-11-02 15:36 UTC, zloyden commented on filters/ThirdParty/filter_216_PolskiFiltr/metadata.json
> +  "description": "Polish supplement for EasyList",
According to your description changes, there is no dot `.` at the end before the second `"`. Is that how it should be?
In most descriptions, I see a dot at the end, and in some I don't.

2020-11-02 15:57 UTC, el-termikael requested changes

2020-11-02 15:57 UTC, el-termikael commented on filters/ThirdParty/filter_232_KADPrzekrety/metadata.json
> +  "description": "Filter that protect against various types of scams, such as SMS subscriptions, fake online stores, etc.",
protect**s**
а ещё SMS subscriptions – это массовые рассылки? тогда лучше mass text messaging или bulk texting

2020-11-02 15:57 UTC, el-termikael commented on filters/ThirdParty/filter_237_PolishAnnoyance/metadata.json
> +  "description": "Filter list that hides and blocks pop-ups, widgets, newsletters, push notifications, arrows, tagged internal links that are off-topic, and other irritating elements. Polskie Filtry
Polskie Filtry Ciasteczkowe is already included **in it**?

2020-11-02 15:57 UTC, el-termikael commented on filters/ThirdParty/filter_245_AlleBlock/metadata.json
> +  "description": "Filters that removes annoying elements from Polish e-commerce sites.",
Filters that remove или Filter that removes
там один или много?

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.123.description": "Hide and block social content, social widgets, social scripts and social icons. Already included in Fanboy's Annoyances list."
Hides and blocks

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.203.description": "Filter list that specifically removes ads on websites in Hungarian language."
in the Hungarian language

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.204.description": "Let us be blinked at no longer! Let the flashing cease! Down with banners! Up with transfer rates! STOP THE MADNESS!"
be blinked at – это как, пассивная конструкция от «закрывать глаза на»?

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.227.description": "Filter that enables removing of ads, trackers, and various scripts from websites with Korean content. Based on Corset, Korean Adblock filter, Youslist. Combined and augme
enables removing of –> removes

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.232.description": "Filter that protect against various types of scams, such as SMS subscriptions, fake online stores, etc."
protects
и опять же SMS subscriptions заменила бы на mass text messages/bulk texting

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.239.description": "A filter to block third-party fonts. It may break the look and design of some websites."
по аналогии с другими описаниями лучше начать с Filter that blocks

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.242.description": "This filter disables browser based miners such as coin-hive."
browser-based

2020-11-02 15:57 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.245.description": "Filters that removes annoying elements from Polish e-commerce sites."
Filter that removes или Filters that remove

2020-11-06 10:01 UTC, zloyden commented
Everything seems to be fine. @el-termikael please take a look.

2020-11-06 10:42 UTC, el-termikael approved these changes

2020-11-06 10:44 UTC, ameshkov approved these changes

2020-11-06 10:46 UTC, merged