Add locales validator
AdguardTeam/FiltersRegistry pull request #396
Opened 2020-11-11 21:53 UTC by slavaleleka

https://github.com/AdguardTeam/FiltersCompiler/issues/94

2020-11-11 21:57 UTC, slavaleleka commented
adguard-filters-compiler should be updated to 1.1.3 here (when it's ready)

2020-11-27 16:33 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.101.description": "EasyList is the primary subscription that removes adverts from web pages in English language. Already included in AdGuard Base filter."
in English language —> in the English language или  in English

2020-11-27 16:41 UTC, el-termikael approved these changes

2020-11-30 12:16 UTC, ameshkov approved these changes

2020-12-01 10:56 UTC, el-termikael requested changes

2020-12-01 10:56 UTC, el-termikael commented on filters/ThirdParty/filter_237_PolishAnnoyance/metadata.json
> +  "name": "Polish Annoyance Filters",
Annoyances 
(по аналогии с AdGuard Annoyances filter и Fanboy's Annoyances)

2020-12-01 10:56 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.220.name": "CJX's Annoyance List",
Annoyances

2020-12-01 10:56 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.237.name": "Polish Annoyance Filters",
Annoyances

2020-12-01 10:56 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.240.description": "BarbBlock is a content blocking list with standalone browser extensions for Chrome and Firefox. It blacklists sites which have used DMCA takedowns to force removal from o
which have used --> that have used

2020-12-01 12:16 UTC, el-termikael approved these changes

2020-12-03 08:44 UTC, el-termikael approved these changes

2020-12-03 09:43 UTC, el-termikael approved these changes

2020-12-10 08:19 UTC, el-termikael approved these changes

2021-01-12 09:37 UTC, ameshkov approved these changes

2021-01-12 09:37 UTC, merged