Add info about `platforms` in metadata to README.md
AdguardTeam/FiltersRegistry pull request #434
Opened 2021-03-10 19:42 UTC by tvinzz

2021-03-10 20:44 UTC, slavaleleka commented on README.md
> +    * `platforms` - the list of platforms to compile the filter for. If you need to compile the filter for all platforms remove this property.
можно еще ссылку зашить:
`https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#platform-and-not_platform-hints`

2021-03-14 14:24 UTC, ameshkov requested changes
I don't see the list of platforms that **could** be used.

2021-03-15 08:49 UTC, slavaleleka commented
there is a link to the full list in kb, I'll add an example

2021-03-15 09:39 UTC, ameshkov approved these changes

2021-03-16 08:14 UTC, merged