New filter EasyList Thailand
AdguardTeam/FiltersRegistry pull request #583
Opened 2022-03-07 19:40 UTC by zloyden

According to the https://github.com/AdguardTeam/FiltersRegistry/issues/580 and https://github.com/AdguardTeam/AdguardFilters/issues/110070#issuecomment-1035592185, let's take a look at this filter.

2022-03-08 19:46 UTC, ameshkov requested changes
We'll also need to upload the strings to Crowdin first.

Please ask @slavaleleka how to do it.

2022-03-08 19:46 UTC, ameshkov commented on filters/ThirdParty/filter_252_EasyListThailand/metadata.json
> +  "description": "This fileter helps you block all advertisements on various websites in Thailand",
"fileter"

2022-03-09 11:22 UTC, Alex-302 commented on filters/ThirdParty/filter_252_EasyListThailand/metadata.json
> +  "description": "This fileter helps you block all advertisements on various websites in Thailand",
What about to replace old Thai filter?

2022-03-10 20:54 UTC, Alex-302 approved these changes

2022-03-10 22:22 UTC, slavaleleka approved these changes

2022-03-11 07:09 UTC, AdamWr approved these changes

2022-03-11 09:12 UTC, anastasiia-fedotova commented on locales/en/filters.json
> +		"filter.202.description": "This filter helps you block all advertisements on various websites in Thailand."
Лучше оставить старое описание фильтра. 
Если хочется, можно написать Filter that helps you block ads on Thai sites.

2022-03-11 09:15 UTC, zloyden commented on locales/en/filters.json
> +		"filter.202.description": "This filter helps you block all advertisements on various websites in Thailand."
Оно просто пришло с новым фильтром, но старое также подходит - вернул его.

2022-03-11 09:18 UTC, anastasiia-fedotova approved these changes

2022-03-11 09:41 UTC, zloyden commented
Waiting for translations, do not merge

2022-03-14 09:48 UTC, anastasiia-fedotova commented on locales/tr/filters.json
> +		"filter.6.description": "EasyList Germany + AdGuard Almanca filtresi. Özellikle Almanca sitelerde reklamları engelleyen filtre."
а ты вот тут намеренно заменил Almanya на Germany?

2022-03-14 09:48 UTC, anastasiia-fedotova commented on locales/tr/filters.json
> +		"filter.8.description": "EasyList Dutch + AdGuard Flemenkçe filtresi. Özellikle Flemenkçe sitelerde reklamları engelleyen filtre."
и вот тут тоже - это была намеренная замена?

2022-03-14 09:49 UTC, anastasiia-fedotova commented on locales/tr/filters.json
> +		"filter.224.description": "EasyList China + AdGuard Çince filtresi. Özellikle Çince sitelerde reklamları engelleyen filtre."
и тут тоже?

2022-03-14 09:49 UTC, anastasiia-fedotova commented on locales/tr/tags.json
> +		"tag.16.name": "EasyList Dutch filtre referansı"
и тут тот же вопрос

2022-03-14 10:03 UTC, anastasiia-fedotova approved these changes

2022-03-14 10:38 UTC, slavaleleka approved these changes

2022-03-14 10:57 UTC, merged

2023-06-28 08:32 UTC, krystian3w commented
https://github.com/adblock-thai/thai-ads-filter/issues/25