Translations for filter.252, tags.65 and tags.66
AdguardTeam/FiltersRegistry pull request #598
Opened 2022-03-25 09:54 UTC by zloyden

https://github.com/AdguardTeam/FiltersRegistry/issues/593

2022-03-25 09:57 UTC, slavaleleka commented on locales/en/filters.json
> +		"filter.252.description": "For the first time in known history, this is a filterlist for websites in Serbian, Montenegrin, Croatian and Bosnian. This means that all significant language groups in E
второе предложение как-то выбивается

2022-03-28 08:07 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.252.description": "For the first time in known history, this is a filterlist for websites in Serbian, Montenegrin, Croatian and Bosnian. This means that all significant language groups in E
да и For the first time in known history вначале как-то пафосно
может, просто: This is a filterlist for websites in Serbian, Montenegrin, Croatian, and Bosnian?

2022-03-28 08:08 UTC, el-termikael requested changes

2022-03-28 08:08 UTC, el-termikael commented on locales/en/filters.json
> +		"filter.252.description": "For the first time in known history, this is a filterlist for websites in Serbian, Montenegrin, Croatian and Bosnian. This means that all significant language groups in E
да и For the first time in known history вначале как-то пафосно
может, просто: This is a filterlist for websites in Serbian, Montenegrin, Croatian, and Bosnian?

2022-03-28 08:16 UTC, zloyden commented on locales/en/filters.json
> +		"filter.252.description": "For the first time in known history, this is a filterlist for websites in Serbian, Montenegrin, Croatian and Bosnian. This means that all significant language groups in E
Ага, поменяю.

2022-03-28 08:44 UTC, slavaleleka approved these changes

2022-03-28 11:34 UTC, el-termikael approved these changes

2022-03-28 11:45 UTC, zloyden commented
Do not merge, waiting for translations.

2022-04-04 07:17 UTC, ameshkov commented
@zloyden what about now?

2022-04-04 08:35 UTC, zloyden commented
They are ready now, I will add them here.

2022-04-04 08:49 UTC, el-termikael approved these changes

2022-04-04 08:59 UTC, merged