Disabled abandonded Adblock-Persian list
AdguardTeam/FiltersRegistry pull request #623
Opened 2022-06-14 16:13 UTC by Alex-302

https://github.com/AdguardTeam/FiltersRegistry/issues/617

Next: replace `Iranian filter` by the one of suggested

2022-06-14 16:43 UTC, zloyden reviewed
We should open a new pull request for locales.

2022-06-14 16:43 UTC, zloyden approved these changes

2022-06-14 21:40 UTC, krystian3w approved these changes

2022-06-15 11:23 UTC, AdamWr approved these changes

2022-06-28 09:55 UTC, aalpatkina requested changes

2022-06-28 10:00 UTC, zloyden commented on locales/en/filters.json
> +		"filter.235.description": "The filter list for blocking ads and trackers on Persian language sites."
Ага, поменял.

2022-06-28 10:50 UTC, aalpatkina approved these changes

2022-06-28 10:57 UTC, zloyden commented
Do not merge. Waiting for translations.

2022-06-30 08:54 UTC, zloyden approved these changes

2022-06-30 09:01 UTC, slavaleleka approved these changes

2022-06-30 09:02 UTC, merged