Replacing my lists' subscription URLs due to raw.githubusercontent.com problems
AdguardTeam/FiltersRegistry pull request #728
Opened 2023-02-13 04:57 UTC by DandelionSprout

For unknown reasons (I've received no info from GitHub about it), the sync time between my list edits and the time they show up on `raw.githubusercontent.com`, has recently increased from 5~9min, to somewhere more than 4 *hours*, whereas CDN services and GitLab CI/CD mirroring takes much less than 4 hours before listfixes go live.

It was a 50:50 call whether to use JSDelivr or GitLab, with neither site's ping limits being likely to be affected by Filters Registry's fetching of lists from them; I went with JSDelivr for 3 of them. For *Annoyances List* I used GitLab due to JSDelivr having possible incompatibilites regarding non-suffix files.

2023-02-13 07:16 UTC, zloyden requested changes
@DandelionSprout please also exchange your subscription URLs in templates.

2023-02-13 09:08 UTC, DandelionSprout commented
I'll look into that within 18 hours.

2023-02-13 20:40 UTC, DandelionSprout commented
Having woke up and been made aware of https://github.com/orgs/community/discussions/46691, I'll keep you guys updated on whether `raw.githubusercontent.com` becomes viable again soon or not.

2023-02-13 20:43 UTC, jimaek commented
Let me know if jsDelivr can help with anything :)

2023-02-13 20:47 UTC, DandelionSprout commented
>Let me know if jsDelivr can help with anything :)

Now that you mention it, it seems there's a minor problem with jsDelivr where it tries to download files with file extensions to the local computer instead of displaying them online, e.g. https://cdn.jsdelivr.net/gh/DandelionSprout/adfilt@master/AnnoyancesList

(Adblockers work in such way that I unfortunately can't simply change the filename to `AnnoyancesList.txt` without heavy coordination with adblocker devs and end-users.)

2023-02-13 21:27 UTC, MartinKolarik commented
@DandelionSprout the downloading happens because without the extension we have no way of knowing the correct mime type of the file so we set a generic one, which then Chrome doesn't know how to display. Anyway, it doesn't change anything unless you expect the files to be directly opened by end users. When fetched via JavaScript, those files will work the same way as the ones with extensions.

2023-02-17 11:02 UTC, jimaek commented
If the AdGuard team is interested in a deeper integration we could also setup a custom proxy config for all lists, similar to what we did with Ghost https://www.jsdelivr.com/oss-cdn/ghost

2023-02-20 14:44 UTC, ameshkov commented
@jimaek hi Dmitriy, thank you, but we serve filter lists from our own domain. I guess this may be helpful to other filters maintainers like @DandelionSprout though.

2023-02-20 14:45 UTC, closed without merging