Add a small change for the 10th description
AdguardTeam/FiltersRegistry pull request #730
Opened 2023-02-17 09:51 UTC by zloyden

I've changed `Duckduckgo` to `DuckDuckGo` in 10th description as requested.

2023-02-17 09:54 UTC, aalpatkina approved these changes

2023-02-20 14:04 UTC, Alex-302 approved these changes

2023-02-21 08:19 UTC, aalpatkina approved these changes

2023-02-21 08:50 UTC, Alex-302 requested changes

2023-02-21 08:50 UTC, Alex-302 commented on locales/fi/tags.json
> +		"tag.2.description": "Suunniteltu suojaamaan yksityisyyttäsi estämällä seuranta- ja analytiikkajärjestelmät",
```suggestion
		"tag.2.description": "Suunniteltu suojaamaan yksityisyyttäsi estämällä seuranta- ja analytiikkajärjestelmät.",
```

2023-02-21 08:50 UTC, Alex-302 commented on locales/fi/tags.json
> +		"tag.2.description": "Suunniteltu suojaamaan yksityisyyttäsi estämällä seuranta- ja analytiikkajärjestelmät",
```suggestion
		"tag.2.description": "Suunniteltu suojaamaan yksityisyyttäsi estämällä seuranta- ja analytiikkajärjestelmät.",
```

2023-02-21 08:50 UTC, Alex-302 commented on locales/fi/tags.json
> +		"tag.25.description": "Sisältää viittauksia seurantaestosuodattimeen",
```suggestion
		"tag.25.description": "Sisältää viittauksia seurantaestosuodattimeen.",
```

2023-02-21 09:17 UTC, slavaleleka approved these changes

2023-02-21 11:23 UTC, Alex-302 approved these changes

2023-02-21 12:01 UTC, merged