Differential updates
AdguardTeam/FiltersRegistry pull request #870
Opened 2023-12-12 13:53 UTC by 105th

Add new way of building platforms with adding patches and compress script to reduce repo size.

2023-12-12 14:08 UTC, slavaleleka commented on package.json
> +    "adguard-filters-compiler": "git+https://github.com/AdguardTeam/FiltersCompiler.git#v1.1.115",
зачем откатывать компилер?
```suggestion
    "adguard-filters-compiler": "git+https://github.com/AdguardTeam/FiltersCompiler.git#v1.1.119",
```

2023-12-12 14:10 UTC, 105th commented on package.json
> +    "@adguard/diff-builder": "git+https://github.com/AdguardTeam/DiffBuilder.git#test-dist"
- [ ] поправить путь, когда запаблишим репу

2023-12-12 15:12 UTC, slavaleleka commented on scripts/build/patches.js
> +        (file) => file.endsWith('.patch')
можно експортнуть из дифф-билдера
```
const PATCH_EXTENSION = '.patch';
```

2023-12-12 15:40 UTC, slavaleleka commented on scripts/build/patches.js
> +        (file) => file.includes('filters/') && file.endsWith('.txt')
напоминает `findFilters()` конкретно етим:
```
file.endsWith('.txt') && path.dirname(filePath).includes('filters')
```

2023-12-12 15:52 UTC, slavaleleka commented on scripts/build/clean_filters.js
> +const FOLDER_WITH_OLD_FILTERS = 'temp/platforms';
используется тут и в `scripts/build/patches.js`

можно унести в `scripts/build/constants.js`

2023-12-12 15:55 UTC, slavaleleka commented on scripts/build/clean_filters.js
> +        const endOfFile = /\r\n$/gm.test(oldFilterContent) ? '\r\n' : '\n';
oldFilterContent.endsWith('\r\n') не сработает? чтобы вместо регулярки

2023-12-12 16:00 UTC, slavaleleka commented on scripts/build/clean_filters.js
> +        if (!fs.existsSync(newFilter)) {
а как такое может быть?

2023-12-15 12:19 UTC, 105th commented
@slavaleleka спасибо за коменты, вроде бы всё учёл

2023-12-15 14:39 UTC, ameshkov requested changes
filters и platforms точно нам нужны в пулл реквесте?

2023-12-18 14:28 UTC, slavaleleka commented on .github/workflows/workflow.yaml
> +        run: yarn build:patches --time=3600 --resolution=s
why not `60m` or `1h` ?

2023-12-18 14:29 UTC, slavaleleka commented on README.md
> +Here is the improved version with corrected English:
looks like not needed
```suggestion
```

2023-12-18 14:31 UTC, slavaleleka commented on README.md
> +    yarn auto-build --mode=ours
isn't it `--mode=adguard` ?

2023-12-18 14:36 UTC, slavaleleka commented on README.md
> +    yarn build -i=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,224
it should be 
```suggestion
    yarn auto-build --mode=adguard
```
isn't it?

2023-12-18 14:43 UTC, 105th commented on README.md
> +    yarn build -i=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,224
не совсем, `auto-build` сделает помимо билда ещё билд патчей и пуш комита в текущую ветку

2023-12-18 14:44 UTC, 105th commented on .github/workflows/workflow.yaml
> +        run: yarn build:patches --time=3600 --resolution=s
в коменте написано, что без разницы

2023-12-18 14:52 UTC, slavaleleka commented on scripts/build/patches.js
> +        (file) => file.includes('filters/') && file.endsWith('.txt')
scripts/build/clean_filters.js still contain:
```
    const allFilters = await findFiles(
        FOLDER_WITH_NEW_FILTERS,
        (filePath) => filePath.endsWith('.txt') && filePath.includes('filters/')
    );
```

can be moved to a helper getNewFiltersTxtFiles()

2023-12-20 10:46 UTC, maximtop approved these changes

2023-12-26 11:36 UTC, maximtop approved these changes

2023-12-26 11:38 UTC, ameshkov approved these changes

2023-12-26 11:39 UTC, merged