update report.txt during full filters build
AdguardTeam/FiltersRegistry pull request #932
Opened 2024-04-04 12:45 UTC by slavaleleka

2024-04-04 12:50 UTC, 105th commented
нужно вот тут поправить проверку - https://github.com/AdguardTeam/FiltersRegistry/blob/master/scripts/build/build.js#L46

новые команды и скрипты не нужны - это усложнение

2024-04-04 12:54 UTC, 105th requested changes

2024-04-04 12:54 UTC, 105th commented on scripts/repository/update_report.sh
а для чего нужен отдельный скрипт?

2024-04-04 12:54 UTC, 105th commented on package.json
> +    "push:filters": "bash scripts/repository/update-filters.sh",
чето это какое-то переусложнение, для чего из одной команды делать две?

2024-04-04 12:54 UTC, 105th commented on scripts/auto_build.sh
> +    yarn build
yarn build запустит билд всех фильтров
это обновит фильтры, патчи при этом для них заново не сгенерируются без вызова команды
и затем команда `diff-index` упадёт (https://github.com/AdguardTeam/FiltersRegistry/pull/932/files#diff-37e062931911c64cae1b7cb3116c4c587cae2a2fccc4183b794dd919d1c77289R6), т.к. будут изменения не только в report.txt, а ещё в filters и platforms

2024-04-04 13:00 UTC, 105th commented on scripts/auto_build.sh
> +    yarn build
на мой взгляд, не совсем правильно два раза вызывать один и тот же скрипт билда фильтров, чтобы затем после второго запуска откатить весь результат и оставить только один текстовый файл

2024-04-04 16:15 UTC, 105th commented
можем тогда удалить старый report.txt?
и в .gitignore тоже убрать?

2024-04-04 16:17 UTC, 105th requested changes

2024-04-04 16:17 UTC, 105th commented on scripts/build/build.js
> +const reportPath = rawReportPath.length > 0
мошт на пустую строку всё-таки проверять? длину мы проверяем у массивов

2024-04-04 16:17 UTC, 105th commented on scripts/repository/update.sh
> +git add report-*.txt
при таком кейсе в репу будут попадать частичные репорты и копиться, но кто их будет чистить?

2024-04-04 16:17 UTC, 105th commented on scripts/repository/update.sh
> +git add report-*.txt
там в соседнем файле нижнее подчёркивание, а тут тире

2024-04-04 16:23 UTC, slavaleleka commented
> можем тогда удалить старый report.txt?

он и удален. ет дифф так отображается как-будто он замещен другим файлом

- - -
> и в .gitignore тоже убрать?

не надо. игнорятся файлы `report_DD-MM-YYYY_HH-MM-SS.txt` которые создаются если `--report=<filename>` не указан

2024-04-04 16:25 UTC, slavaleleka commented on scripts/build/build.js
> +const reportPath = rawReportPath.length > 0
поправил

2024-04-04 16:27 UTC, slavaleleka commented on scripts/repository/update.sh
> +git add report-*.txt
> там в соседнем файле нижнее подчёркивание, а тут тире

зделал намеренно так чтобы было явно

2024-04-04 16:33 UTC, 105th commented on scripts/repository/update.sh
> +git add report-*.txt
@slavaleleka 
мысль понял.
а можем ли мы как-то более наглядно это в коде отобразить, например здесь написать:
```
git add report-adguard.txt
git add report-third-party.txt
```

или в частичные добавить постфикс:
```
#.gitignore

report_*_*.txt # -> report_partial_*.txt
```
?

то есть хочется, чтобы не возникало ощущения, что эти две записи в разных файлах это опечатка:
`report_*_*.txt` в .gitignore
и `git add report-*.txt` тут

2024-04-04 16:42 UTC, slavaleleka commented
> А старый report.txt почему не удалили?

удолили

2024-04-04 16:43 UTC, slavaleleka commented
нет больше старого report.txt
https://uploads.adguard.org/sll9y81ycgyv6.png

2024-04-04 16:45 UTC, 105th commented
> А старый report.txt почему не удалили?

https://github.com/AdguardTeam/FiltersRegistry/pull/932#issuecomment-2037658846

2024-04-04 16:46 UTC, 105th approved these changes
нраица

2024-04-04 16:47 UTC, slavaleleka commented on scripts/repository/update.sh
> +git add report-*.txt
```
git add report-adguard.txt
git add report-third-party.txt
```

так написать не получится потому что может ебануть когда одного из двух файлов нет
https://uploads.adguard.org/sll0fqb0bikbh.png

- - -

`report_*_*.txt # -> report_partial_*.txt` — ето поправил

2024-04-04 17:06 UTC, Alex-302 commented
```
URL: https://phishing.army/download/phishing_army_blocklist_extended.txt
INVALID RULES:
Error: Invalid selector: '#ad-carousel$all' -- Error: unable to select by '#ad-carousel$all' — '#ad-carousel$all' is not a valid selector in rule: dez.ro#@##ad-carousel$all
Error: Invalid selector: '#ad-p3$all' -- Error: unable to select by '#ad-p3$all' — '#ad-p3$all' is not a valid selector in rule: so-net.ne.jp#@##ad-p3$all
Error: Invalid selector: '#ad-rotator$all' -- Error: unable to select by '#ad-rotator$all' — '#ad-rotator$all' is not a valid selector in rule: 53.com#@##ad-rotator$all
Error: Invalid selector: '#ad-top$all' -- Error: unable to select by '#ad-top$all' — '#ad-top$all' is not a valid selector in rule: techymedies.com#@##ad-top$all
```

а это что за дичь?

2024-04-04 17:31 UTC, Alex-302 commented
Build does not work on my end.
I use Windows.

![image](https://github.com/AdguardTeam/FiltersRegistry/assets/8361299/71365c14-d8a8-4795-a3f8-0bd2f9ea69d3)


![image](https://github.com/AdguardTeam/FiltersRegistry/assets/8361299/2d3fe571-3af8-40b8-ba7a-47c00700e467)

2024-04-05 15:52 UTC, Alex-302 approved these changes

2024-04-05 15:52 UTC, merged