Fix #946 add optimized cname lists
AdguardTeam/FiltersRegistry pull request #953
Opened 2024-05-20 15:29 UTC by jellizaveta

2024-05-20 15:44 UTC, Alex-302 approved these changes

2024-05-20 15:46 UTC, Alex-302 requested changes

2024-05-20 16:20 UTC, slavaleleka commented on filters/filter_2_Base/template.txt
> +@include "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/clickthroughs/clickaine.txt" /optimizeDomainBlockingRules /exclude="../exclusions.txt"
it is the `clickthroughs` category. is it ok?

2024-05-20 16:21 UTC, slavaleleka approved these changes

2024-05-21 06:29 UTC, zloyden approved these changes

2024-05-21 07:14 UTC, piquark6046 approved these changes

2024-05-21 11:15 UTC, Alex-302 commented
https://github.com/AdguardTeam/AdguardFilters/pull/179645/files#diff-d38ad709373222a99d2a34c309f92aa2cf8da4070ba73711e6419c537bb4d80aL12-L14

this file is not so large now, ~5k rules, 3700 may be removed during optimization (need to extract corresponding rules before that)

2024-05-22 11:24 UTC, Alex-302 approved these changes

2024-05-22 11:24 UTC, zloyden approved these changes

2024-05-22 17:01 UTC, merged